import PDFDocument from 'pdfkit';
import { IFeedbackReport } from '../features/feedback/model/feedback.model';

export const generateFeedbackPDF = (report: IFeedbackReport, candidateName: string, targetRole: string, interviewType: string): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (err) => reject(err));

    // Header
    doc.fontSize(20).text('Interview Feedback Report', { align: 'center' });
    doc.moveDown();

    // Basic Info
    doc.fontSize(12).text(`Candidate Name: ${candidateName}`);
    doc.text(`Target Role: ${targetRole}`);
    doc.text(`Interview Type: ${interviewType}`);
    doc.text(`Date: ${new Date(report.createdAt).toLocaleDateString()}`);
    doc.moveDown();

    // Scores
    doc.fontSize(16).text('Scores', { underline: true });
    doc.fontSize(12).text(`Overall Score: ${report.overallScore}/100`);
    doc.text(`Technical Score: ${report.technicalScore}/100`);
    doc.text(`Problem Solving: ${report.problemSolvingScore}/100`);
    doc.text(`Communication: ${report.communicationScore}/100`);
    doc.moveDown();

    // Summary
    doc.fontSize(16).text('Executive Summary', { underline: true });
    doc.fontSize(12).text(report.summary);
    doc.moveDown();

    // Strengths
    doc.fontSize(16).text('Strengths', { underline: true });
    report.strengths.forEach(s => doc.fontSize(12).text(`• ${s.topic}: ${s.description}`));
    doc.moveDown();

    // Weaknesses
    doc.fontSize(16).text('Areas for Improvement', { underline: true });
    report.weaknesses.forEach(w => doc.fontSize(12).text(`• ${w.topic}: ${w.description}`));
    doc.moveDown();

    // Recommendations
    doc.addPage();
    doc.fontSize(16).text('Actionable Recommendations', { underline: true });
    report.recommendations.forEach(r => {
      doc.fontSize(12).text(`• [${r.category}] ${r.actionableStep}`);
    });
    doc.moveDown(2);

    // Disclaimer footer
    doc.fontSize(10).fillColor('gray').text(
      'Disclaimer: This report is generated by an AI assistant for advisory purposes only and does not represent a final hiring decision.',
      { align: 'center', baseline: 'bottom' }
    );

    doc.end();
  });
};
