import PDFDocument from 'pdfkit';
import { IFeedbackReport } from '../features/feedback/model/feedback.model';

export const generateFeedbackPDF = (report: IFeedbackReport, candidateName: string, targetRole: string, interviewType: string): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (err) => reject(err));

    const brandColor = '#4F46E5';
    const textDark = '#1F2937';
    const textLight = '#6B7280';

    // Header Background
    doc.rect(0, 0, doc.page.width, 120).fill(brandColor);
    
    doc.fillColor('white').fontSize(28).font('Helvetica-Bold')
       .text('Interview Feedback Report', 50, 40);
    doc.fontSize(12).font('Helvetica')
       .text('Generated by HackInMotion AI', 50, 75);

    doc.moveDown(4);

    // Basic Info Block
    doc.rect(50, 140, doc.page.width - 100, 70).fill('#F3F4F6').stroke('#E5E7EB');
    doc.fillColor(textDark).fontSize(12).font('Helvetica-Bold')
       .text(`Candidate:`, 70, 155).font('Helvetica').text(candidateName, 140, 155)
       .font('Helvetica-Bold').text(`Target Role:`, 70, 175).font('Helvetica').text(targetRole, 140, 175);
    
    doc.font('Helvetica-Bold').text(`Type:`, 350, 155).font('Helvetica').text(interviewType, 400, 155)
       .font('Helvetica-Bold').text(`Date:`, 350, 175).font('Helvetica').text(new Date(report.createdAt).toLocaleDateString(), 400, 175);

    doc.moveDown(3);

    // Helper for section headers
    const addSectionHeader = (title: string, yOffset?: number) => {
      if (yOffset) doc.y = yOffset;
      doc.fillColor(brandColor).fontSize(16).font('Helvetica-Bold').text(title);
      doc.moveTo(50, doc.y + 5).lineTo(doc.page.width - 50, doc.y + 5).stroke(brandColor);
      doc.moveDown(1.5);
      doc.fillColor(textDark);
    };

    const getScoreColor = (score: number) => score >= 80 ? '#10B981' : (score >= 60 ? '#F59E0B' : '#EF4444');

    // Scores Section
    addSectionHeader('Performance Scores');
    
    // Overall Score
    doc.fontSize(14).font('Helvetica-Bold').text('Overall Score: ', { continued: true })
       .fillColor(getScoreColor(report.overallScore)).fontSize(16).text(`${Math.round(report.overallScore)}/100`);
    
    doc.moveDown(1);
    doc.fillColor(textDark).fontSize(12).font('Helvetica');
    
    const scores = [
      { label: 'Technical Score', value: report.technicalScore },
      { label: 'Problem Solving', value: report.problemSolvingScore },
      { label: 'Communication', value: report.communicationScore },
      { label: 'Coding', value: report.codingScore },
      { label: 'Behavioral', value: report.behavioralScore }
    ];

    let startX = 50;
    let startY = doc.y;
    scores.forEach((s, i) => {
      if (i === 3) { startX = 300; startY -= 60; }
      doc.text(`${s.label}: `, startX, startY).fillColor(getScoreColor(s.value || 0))
         .text(`${Math.round(s.value || 0)}/100`, startX + 110, startY);
      doc.fillColor(textDark);
      startY += 20;
    });

    doc.y = Math.max(doc.y, startY) + 30;

    // Summary
    addSectionHeader('Executive Summary');
    doc.fontSize(12).font('Helvetica').text(report.summary || 'Summary unavailable.', { align: 'justify', lineGap: 4 });
    doc.moveDown(2);

    // Helper for lists
    const addList = (items: any[], isWeakness = false) => {
      (items || []).forEach(item => {
        doc.fillColor(isWeakness ? '#EF4444' : '#10B981').circle(55, doc.y + 5, 3).fill();
        doc.fillColor(textDark).font('Helvetica-Bold').text(`${item.topic || 'General'}: `, 65, doc.y, { continued: true })
           .font('Helvetica').text(item.description || '', { lineGap: 2 });
        doc.moveDown(0.5);
      });
    };

    // Strengths
    addSectionHeader('Key Strengths');
    addList(report.strengths, false);
    doc.moveDown(1.5);

    // Weaknesses
    addSectionHeader('Areas for Improvement');
    addList(report.weaknesses, true);
    doc.moveDown(1.5);

    // Recommendations
    if (doc.y > doc.page.height - 150) doc.addPage();
    addSectionHeader('Actionable Recommendations');
    (report.recommendations || []).forEach(r => {
      doc.fillColor(brandColor).rect(50, doc.y, 5, 5).fill();
      doc.fillColor(textDark).font('Helvetica-Bold').text(`[${r.category || 'General'}]`, 65, doc.y, { continued: true })
         .font('Helvetica').text(` ${r.actionableStep || ''}`, { lineGap: 2 });
      doc.moveDown(1);
    });

    // Footer
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(9).fillColor(textLight)
         .text(
           'Disclaimer: This report is generated by an AI assistant for advisory purposes only.',
           50, doc.page.height - 50, { align: 'center' }
         );
    }

    doc.end();
  });
};
